default: &default
  url: <%= ENV["DB_URL"] %>
  adapter: postgresql
development:
  <<: *default
  database: weather-dev
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
test:
  <<: *default
  database: weather-test
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
production:
  <<: *default
  database: weather-prod
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
staging:
  <<: *default
  database: weather-stage
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
